public with sharing class TRIGGER_HANDLER_FILENAME extends ZennSObjectDomain{
	public TRIGGER_HANDLER_FILENAME() {
		super(TRIGGER_SOBJECT.sObjectType);
	}

	protected override void onBeforeExecute(){
		//Stuff to do BEFORE Trigger Events
	}

	protected override void onAfterExecute() {
		//Stuff to do AFTER Trigger Events
	}

	protected override void onBeforeInsert(){

	}

	protected override void onAfterInsert(){

	}

	protected override void onBeforeUpdate(){

	}

	protected override void onAfterUpdate(){

	}

	protected override void onBeforeDelete(){

	}

	protected override void onAfterDelete(){

	}

	protected override void onAfterUndelete(){

	}
}